<?php include '../top.php'; ?>

<main>
    <article>
        <p>30% of the profit from the photos that we sell goes to a national park of your choosing to preserve the beauty in nature that we try to capture in each and every photo we take. Without nature and national parks our company would not have become what it is today as it is the focal point of our photography. And we want to share our appreciation for the landscape so that others, who may not have the convenience of being within nature can see what we see. How our lands have shaped our nation and how they support and uplift us in our rushed and diminutive lives. We believe that it is time to support our lands as they support us and give back to these national reserves that so greatly need our help. With carbon dioxide levels rising and forest areas drastically being reduced the plants of the wild are working overtime to keep up and maintain life, our lives, on this planet. And as a thank you, we wanted to do what we can to give back to the things that give us such a powerful gift, and while it may seem like a minuscule act it is one step towards a better future full of life and a planet of appreciation to the things that allow us to live.</p>
        <p>These photos were all taken around the United States. There may even be some places that you recognize from your favorite hikes or coffee shops around town. They represent many styles and places. From the faces we may recognize, to those we have never met. From joyous events to somber occasions. The photographers who took them receive 60% of the profit so that they may continue doing the beautiful work that they do. So they can continue opening up different ways of viewing the same places in order to challenge the minds of others as well as their own and share their favorite places. </p>
        <p>We believe that beauty and intricacy can be found anywhere no matter the circumstance. And these pictures work to show you such things. They also wish to inspire in such a way that one may look at one single aspect of the world at a slightly different angle. They challenge the mind’s thoughts and opinions on subjects great and small. These are pictures that wish to make a change by artists who wish to make a change. Whatever their cause, we support their efforts as if they were our own and we hope that in viewing these photos that you at least listen to their messages. Because without someone to view them, pictures are just pictures, without meaning. It is you, the people who come across this site, either by accident or purposefully, that make a picture a picture. You give the picture meaning, because, a story told to no-one is a story without purpose. So, we want to give back to you what you have given to us. A meaning, a story, an inspiration. </p>
    </article>
</main>

<?php include '../footer.php' ?>

</body>
</html>